// 실행: node test_web_ui.mjs. 사용자 탐색 화면의 읽기 전용 계약 검사.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';

const html = readFileSync(new URL('./web.html', import.meta.url), 'utf8');
assert.match(html, /data-filter="ai-ml agents-automation"/);
assert.match(html, /id="search"/);
assert.match(html, /id="sort"/);
assert.match(html, /id="clear"/);
assert.match(html, /selected=selected===r\.repo\?'':r\.repo/);
assert.match(html, /feed\.querySelectorAll\('\.card'\)/);
assert.doesNotMatch(html, /selected=selected===r\.repo\?'':r\.repo;cards\(\)/);
assert.match(html, /a\.href=x\.url/);
assert.match(html, /x\.user\?'@'\+x\.user:'작성자 미상'/);
assert.match(html, /x\.created_at\.slice\(5,10\)\.replace\('-','\.'\)/);
assert.match(html, /x\.grade\?\.difficulty\?'난이도 '\+x\.grade\.difficulty:'난이도 미정'/);
assert.match(html, /ready:'바로 착수',needs_info:'확인 필요',undecided:'판단 보류'/);
assert.match(html, /if\(x\.error\)return'판정 실패'/);
assert.match(html, /if\(!x\.grade\)return'미판정'/);
assert.match(html, /if\(x\.grade\.exclude\)return'제외'/);
assert.match(html, /make\('div','repo-head'\)/);
assert.match(html, /r\.description\+' · 이슈 '\+rows\.length\+'개'/);
assert.match(html, /av\.onerror=\(\)=>av\.hidden=true/);
assert.match(html, /slot=make\('span','avatar-slot'\)/);
assert.match(html, /fetch\('\/data\.json'\)/);
assert.match(html, /opengraph\.githubassets\.com\/1\//);
assert.match(html, /avatars\.githubusercontent\.com/);
assert.match(html, /r\.repository_image\|\|social/);
assert.match(html, /img\.className='social'/);
assert.match(html, /img\.naturalWidth\*p\.clientHeight>img\.naturalHeight\*p\.clientWidth/);
assert.match(html, /fallback\.hidden=true/);
assert.match(html, /img\.hidden=true;fallback\.hidden=false/);
assert.match(html, /const cardCache=new Map/);
assert.match(html, /let b=cardCache\.get\(r\.repo\)/);
assert.match(html, /cardCache\.set\(r\.repo,b\)/);
assert.match(html, /\.side\{position:sticky;top:0;width:360px;height:100vh;overflow-y:auto/);
assert.match(html, /\['e',0\],\['m',1\],\['h',2\]/);
assert.doesNotMatch(html, /\/api\/run/);
assert.doesNotMatch(html, /id="collect"/);
assert.doesNotMatch(html, /id="grade"/);
console.log('통과: 탐색·검색·정렬·레포 선택·원본 이슈 이동과 운영 기능 비노출');
